[tool.black]
line-length = 99
target-version = ["py311"]
skip-string-normalization = false

[tool.ruff]
line-length = 99
target-version = "py311"

[tool.ruff.lint]
select = [
  "E", "W",   # pycodestyle (PEP 8 checks)
  "F",        # pyflakes
  "I",        # import sorting (isort)
  "UP",       # pyupgrade
  "SIM",      # simplify
  "N",        # naming
  "B",        # bugbear
  "C4",       # comprehensions
  "TID",      # tidy imports
]
ignore = ["T201",  "D103", "D107", "B018"]
# T201 - print() occurrences
# D103 - missing function docstrings
# D107 - missing class docstrings
# B018 - unused loop vars

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["yourpkg"]

[tool.pydocstyle]
ignore = ["D100", "D101", "D102", "D103", "D107"]
